# Generated by Django 5.1.3 on 2024-11-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
